const defaultVehicles=[
{id:crypto.randomUUID(),name:'Ford Mustang Mach‑E',plate:'7AC 1234',type:'Osobní automobil',year:'2021',km:'60000',vin:'',doc:null,serviceHistory:[]},
{id:crypto.randomUUID(),name:'Volkswagen Touareg',plate:'6BC 5678',type:'Osobní automobil',year:'2004',km:'',vin:'',doc:null,serviceHistory:[]},
{id:crypto.randomUUID(),name:'Pongratz LPA 206 U',plate:'5E9 9012',type:'Přívěsný vozík',year:'',km:'',vin:'',doc:null,serviceHistory:[]}
];
let vehicles=JSON.parse(localStorage.getItem('garageVehicles')||'null')||defaultVehicles;
vehicles.forEach(v=>{if(!Array.isArray(v.serviceHistory))v.serviceHistory=[]});
let activeView='garage';
let activeVehicleId=null;
const premiumUnlocked=true;
const main=document.querySelector('#main');
const vehicleDialog=document.querySelector('#vehicleDialog');
const vehicleForm=document.querySelector('#vehicleForm');
const docDialog=document.querySelector('#docDialog');
const docForm=document.querySelector('#docForm');
const premiumDialog=document.querySelector('#premiumDialog');
function save(){localStorage.setItem('garageVehicles',JSON.stringify(vehicles));}
function icon(type){if(type.includes('Přívěs'))return '🛻';if(type.includes('Mot'))return '🏍️';if(type.includes('Dod'))return '🚐';return '🚙'}
function daysFromToday(d){if(!d)return null;const [y,m,day]=d.split('-').map(Number);const today=new Date();today.setHours(0,0,0,0);const target=new Date(y,m-1,day);target.setHours(0,0,0,0);return Math.round((target-today)/86400000)}
function deadlineText(d,prefix='do '){const days=daysFromToday(d);if(days===null)return'';if(days<0)return `PO TERMÍNU ${Math.abs(days)} ${Math.abs(days)===1?'DEN':'DNÍ'} · ${formatDate(d)}`;if(days===0)return `DNES · ${formatDate(d)}`;return prefix+formatDate(d)}
function overdueItems(){const out=[];vehicles.forEach(v=>{[['stkDate','STK'],['oilDate','výměna oleje'],['reminderDate','připomínka']].forEach(([key,label])=>{const diff=v[key]?daysFromToday(v[key]):null;if(diff!==null&&diff<0)out.push({vehicle:v.name,label,date:v[key],days:Math.abs(diff)})})});return out}
function renderGarage(){
 activeVehicleId=null;
 const overdue=overdueItems();
 const alertBanner=overdue.length?`<section class="page-card" style="border:2px solid #ef4444;background:#fff1f2;margin-bottom:14px"><div style="font-size:12px;font-weight:800;color:#b91c1c;letter-spacing:.08em">⚠️ NĚCO UTEKLO</div><h3 style="margin:6px 0 4px">${overdue.length===1?'Máš 1 termín po lhůtě':`Máš ${overdue.length} termíny po lhůtě`}</h3><p style="margin:0;color:#991b1b">${esc(overdue[0].vehicle)} · ${esc(overdue[0].label)} je ${overdue[0].days} ${overdue[0].days===1?'den':'dní'} po termínu.${overdue.length>1?' A další '+(overdue.length-1)+'.':''}</p></section>`:'';
 main.innerHTML=`${alertBanner}<button class="primary add-btn" id="addVehicle">＋ Přidat vozidlo</button><div class="section-title"><h3>Vozidla</h3><span class="count">${vehicles.length} položky</span></div><div id="vehicleList"></div><section class="premium-banner"><div class="eyebrow gold">♛ PREMIUM</div><h3>Už nikdy na nic nezapomeň</h3><p>STK, výměny oleje, pneumatiky a další termíny s upozorněním.</p><button class="premium-cta" id="showPremium">Premium odemčeno ✓</button></section>`;
 const list=document.querySelector('#vehicleList');
 if(!vehicles.length)list.innerHTML='<div class="empty">Zatím tu nic není. Přidej první auto nebo vozík.</div>';
 vehicles.forEach(v=>{const c=document.createElement('article');c.className='vehicle-card';const stkOver=v.stkDate&&daysFromToday(v.stkDate)<0,oilOver=v.oilDate&&daysFromToday(v.oilDate)<0,remOver=v.reminderDate&&daysFromToday(v.reminderDate)<0;c.innerHTML=`<div class="vehicle-top vehicle-open" data-id="${v.id}" style="cursor:pointer"><div class="vehicle-avatar">${icon(v.type)}</div><div class="vehicle-title"><h3>${esc(v.name)} <span style="font-size:14px;color:#94a3b8">›</span></h3><span class="plate">🇨🇿 ${esc(v.plate)}</span><div class="meta">${esc(v.type)}${v.year?' · '+esc(v.year):''}${v.km?' · '+Number(v.km).toLocaleString('cs-CZ')+' km':''}</div></div></div><div class="quick-row"><button class="quick free doc-btn" data-id="${v.id}"><strong>🟢 Zelená karta</strong><span>${v.doc?('uložena'+(v.doc.validTo?' · do '+formatDate(v.doc.validTo):'')):'přidat dokument'}</span></button><button class="quick premium service-btn" data-id="${v.id}" data-kind="stk" ${stkOver?'style="border:2px solid #ef4444;background:#fff1f2"':''}><strong>${stkOver?'🔴':'🟡'} STK</strong><span>${v.stkDate?deadlineText(v.stkDate):'nastavit termín'}</span></button><button class="quick premium service-btn" data-id="${v.id}" data-kind="oil" ${oilOver?'style="border:2px solid #ef4444;background:#fff1f2"':''}><strong>${oilOver?'🔴':'🛢️'} Výměna oleje</strong><span>${v.oilDate?deadlineText(v.oilDate):'nastavit termín'}</span></button><button class="quick locked service-btn" data-id="${v.id}" data-kind="reminder" ${remOver?'style="border:2px solid #ef4444;background:#fff1f2"':''}><strong>${remOver?'🔴':'🔔'} Upozornění</strong><span>${v.reminderDate?deadlineText(v.reminderDate,'na '):'nastavit'}</span></button></div>`;list.appendChild(c)});
 document.querySelector('#addVehicle').onclick=()=>vehicleDialog.showModal();document.querySelector('#showPremium').onclick=()=>{activeView='terms';render()};document.querySelectorAll('.vehicle-open').forEach(b=>b.onclick=()=>renderVehicleDetail(b.dataset.id));document.querySelectorAll('.service-btn').forEach(b=>b.onclick=()=>setService(b.dataset.id,b.dataset.kind));document.querySelectorAll('.doc-btn').forEach(b=>b.onclick=()=>openDoc(b.dataset.id));
}
function renderVehicleDetail(id){
 const v=vehicles.find(x=>x.id===id);if(!v){activeView='garage';render();return}activeVehicleId=id;
 const hist=[...(v.serviceHistory||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||''));
 const historyHtml=hist.length?hist.map(h=>`<div class="page-card" style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><strong>${esc(h.title)}</strong><div class="meta">${formatDate(h.date)}${h.km?' · '+Number(h.km).toLocaleString('cs-CZ')+' km':''}${h.price?' · '+Number(h.price).toLocaleString('cs-CZ')+' Kč':''}</div>${h.note?`<div style="margin-top:6px;font-size:14px">${esc(h.note)}</div>`:''}${h.fileName?`<div style="margin-top:7px;font-size:13px;color:#2563eb">📎 ${esc(h.fileName)}</div>`:''}</div><button class="delete-service" data-sid="${h.id}" style="border:0;background:transparent;color:#94a3b8;font-size:18px">×</button></div></div>`).join(''):'<div class="empty">Zatím žádný servisní záznam.</div>';
 main.innerHTML=`<button id="backGarage" style="border:0;background:transparent;padding:4px 0 14px;font-weight:700;color:#2563eb">‹ Zpět do garáže</button>
 <section class="page-card"><div style="display:flex;gap:14px;align-items:center"><div class="vehicle-avatar" style="width:58px;height:58px">${icon(v.type)}</div><div><h2 style="margin:0 0 5px">${esc(v.name)}</h2><span class="plate">🇨🇿 ${esc(v.plate)}</span><div class="meta" style="margin-top:5px">${esc(v.type)}${v.year?' · '+esc(v.year):''}${v.km?' · '+Number(v.km).toLocaleString('cs-CZ')+' km':''}</div></div></div></section>
 <section class="page-card"><h3 style="margin-top:0">Aktuální termíny</h3><div class="term"><div><strong>STK</strong><div class="meta">${v.stkDate?deadlineText(v.stkDate):'Nenastaveno'}</div></div></div><div class="term"><div><strong>Výměna oleje</strong><div class="meta">${v.oilDate?deadlineText(v.oilDate):'Nenastaveno'}</div></div></div><div class="term"><div><strong>Zelená karta</strong><div class="meta">${v.doc?esc(v.doc.fileName||'Uložena'):'Nenahrána'}</div></div></div></section>
 <section class="page-card"><h3 style="margin-top:0">＋ Přidat servisní záznam</h3><form id="serviceHistoryForm" style="display:grid;gap:10px"><input name="title" required placeholder="Co se dělalo – např. výměna oleje" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid #dbe2ea;border-radius:12px;font-size:16px"><input name="date" required inputmode="numeric" placeholder="Datum – 28082026" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid #dbe2ea;border-radius:12px;font-size:16px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input name="km" inputmode="numeric" placeholder="Stav km" style="min-width:0;padding:12px;border:1px solid #dbe2ea;border-radius:12px;font-size:16px"><input name="price" inputmode="numeric" placeholder="Cena Kč" style="min-width:0;padding:12px;border:1px solid #dbe2ea;border-radius:12px;font-size:16px"></div><textarea name="note" placeholder="Poznámka" rows="2" style="width:100%;box-sizing:border-box;padding:12px;border:1px solid #dbe2ea;border-radius:12px;font-size:16px"></textarea><label style="font-size:14px;font-weight:700">Doklad / faktura<input name="file" type="file" accept="image/*,.pdf" style="display:block;width:100%;margin-top:7px;font-size:15px"></label><button class="primary" type="submit">Uložit servisní záznam</button></form></section>
 <div class="section-title"><h3>Servisní historie</h3><span class="count">${hist.length} záznamů</span></div>${historyHtml}`;
 document.querySelector('#backGarage').onclick=()=>{activeView='garage';render()};
 document.querySelector('#serviceHistoryForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const date=parseCzechDate(f.get('date'));if(!date){alert('Datum zadej jako 28082026 nebo 28.08.2026.');return}const file=e.currentTarget.file.files[0];v.serviceHistory=v.serviceHistory||[];v.serviceHistory.push({id:crypto.randomUUID(),title:String(f.get('title')||'').trim(),date,km:String(f.get('km')||'').replace(/\D/g,''),price:String(f.get('price')||'').replace(/\D/g,''),note:String(f.get('note')||'').trim(),fileName:file?.name||''});save();renderVehicleDetail(id)});
 document.querySelectorAll('.delete-service').forEach(b=>b.onclick=()=>{if(confirm('Smazat tento servisní záznam?')){v.serviceHistory=(v.serviceHistory||[]).filter(h=>h.id!==b.dataset.sid);save();renderVehicleDetail(id)}})
}
function renderTerms(){
 const rows=[];
 vehicles.forEach(v=>{
  if(v.stkDate) rows.push(`<div class="term"><div><strong>${esc(v.name)} · STK</strong><div class="meta">${deadlineText(v.stkDate,'Platnost do ')}</div></div><span class="pill premium">${daysFromToday(v.stkDate)<0?'PO TERMÍNU':'AKTIVNÍ'}</span></div>`);
  if(v.oilDate) rows.push(`<div class="term"><div><strong>${esc(v.name)} · Olej</strong><div class="meta">${deadlineText(v.oilDate,'Termín ')}</div></div><span class="pill premium">${daysFromToday(v.oilDate)<0?'PO TERMÍNU':'AKTIVNÍ'}</span></div>`);
  if(v.reminderDate) rows.push(`<div class="term"><div><strong>${esc(v.name)} · Připomínka</strong><div class="meta">${deadlineText(v.reminderDate,'')}</div></div><span class="pill premium">${daysFromToday(v.reminderDate)<0?'PO TERMÍNU':'AKTIVNÍ'}</span></div>`);
 });
 main.innerHTML=`<div class="page-card"><h2>Termíny</h2><p class="lead">Premium je pro testování odemčené ✓</p></div><div class="page-card">${rows.length?rows.join(''):'<div class="empty">Termíny nastavíš přímo u jednotlivých vozidel v Garáži.</div>'}</div>`;
}
function renderDocs(){const docs=vehicles.filter(v=>v.doc);main.innerHTML=`<div class="page-card"><h2>Dokumenty</h2><p class="lead">Zelené karty máš zdarma.</p></div>${docs.length?docs.map(v=>`<div class="page-card"><strong>${esc(v.name)}</strong><div class="meta">${esc(v.plate)} · ${esc(v.doc.fileName||'Zelená karta')}${v.doc.validTo?' · platnost do '+formatDate(v.doc.validTo):''}</div></div>`).join(''):'<div class="empty">Zatím nemáš uloženou žádnou zelenou kartu.</div>'}`}
function renderMore(){main.innerHTML=`<div class="page-card"><h2>Více</h2><div class="term"><div><strong>Účet a synchronizace</strong><div class="meta">Připravíme pro ostrou verzi</div></div><span class="pill">BRZY</span></div><div class="term"><div><strong>Export dat</strong><div class="meta">Záloha vozidel a dokumentů</div></div><span class="pill">BRZY</span></div><div class="term"><div><strong>Premium</strong><div class="meta">STK, olej, notifikace a servis</div></div><span class="pill premium">PREMIUM</span></div></div>`}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===activeView));({garage:renderGarage,terms:renderTerms,docs:renderDocs,more:renderMore})[activeView]()}
function openDoc(id){docForm.reset();docForm.vehicleId.value=id;document.querySelector('#docFileName').textContent='';docDialog.showModal()}
vehicleForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(vehicleForm);vehicles.unshift({id:crypto.randomUUID(),name:f.get('name'),plate:f.get('plate'),type:f.get('type'),year:f.get('year'),km:f.get('km'),vin:f.get('vin'),doc:null,serviceHistory:[]});save();vehicleDialog.close();vehicleForm.reset();render()});
docForm.file.addEventListener('change',()=>document.querySelector('#docFileName').textContent=docForm.file.files[0]?.name||'');docForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(docForm),v=vehicles.find(x=>x.id===f.get('vehicleId'));if(v){v.doc={validTo:f.get('validTo'),fileName:docForm.file.files[0]?.name||'Zelená karta'};save()}docDialog.close();render()});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{activeView=b.dataset.view;activeVehicleId=null;render()});document.querySelector('#notifBtn').onclick=()=>{activeView='terms';activeVehicleId=null;render()};
function parseCzechDate(s){const raw=String(s||'').trim().replace(/\s+/g,'');let d,m,y;if(/^\d{8}$/.test(raw)){d=Number(raw.slice(0,2));m=Number(raw.slice(2,4));y=Number(raw.slice(4,8));}else{const match=raw.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(!match)return null;d=Number(match[1]);m=Number(match[2]);y=Number(match[3]);}const dt=new Date(y,m-1,d);if(dt.getFullYear()!==y||dt.getMonth()!==m-1||dt.getDate()!==d)return null;return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function compactDate(d){if(!d)return'';const [y,m,day]=d.split('-');return `${day}.${m}.${y}`}
function setService(id,kind){const v=vehicles.find(x=>x.id===id);if(!v)return;const labels={stk:'Datum platnosti STK — napiš třeba 01082026 nebo 01.08.2026',oil:'Datum příští výměny oleje — napiš třeba 01082026 nebo 01.08.2026',reminder:'Datum připomínky — napiš třeba 01082026 nebo 01.08.2026'};const keys={stk:'stkDate',oil:'oilDate',reminder:'reminderDate'};const current=v[keys[kind]]?compactDate(v[keys[kind]]):'';const val=prompt(labels[kind],current);if(val===null)return;if(!val.trim()){v[keys[kind]]='';save();render();return;}const parsed=parseCzechDate(val);if(!parsed){alert('Zadej datum jako 01082026 nebo 01.08.2026. Lze zadat i datum v minulosti.');return;}v[keys[kind]]=parsed;save();render();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function formatDate(d){if(!d)return'';const [y,m,day]=d.split('-');return `${Number(day)}. ${Number(m)}. ${y}`}
save();render();
